### ISSUE TITLE
Why this over react-native-sound?

### ISSUE THREAD

**Issue by Noitidart** [luminos-software/react-native-play-sound#1]
Thanks for writing a nice lib and sharing it. However what is the advantage of this lib over react-native-sound - https://github.com/zmxv/react-native-sound#react-native-sound ?

**Comment by ghitatomy** [comment]
The main advantage is no need to use cocoapods – this can make setup a little easier for devs that don’t want to dig so much into native technologies. There’s also a fractional saving on memory (0.05 MB) if you’re concerned about support for devices with very little memory :)

**Comment by Noitidart** [comment]
Thanks @ghitatomy - I'm not sure we have to use cocoapods for react-native-sound. I never did.

**Comment by ghitatomy** [comment]
You can look and see they have a podspec file that is for cocoapods.

**Comment by Noitidart** [comment]
Ohh interesting, thanks! It's weird I don't know why they have it, I never used pod install for it though. It just works.

**Comment by ghitatomy** [comment]
That's because you don't use pods in the project. If you have a pod file in ios folder you can see it  there after you linked.
